wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682603360.093184
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 1
      - 3
      - 19
      - 23
      4: 3.9.16
      5: 0.15.0
      8:
      - 5
batch_size:
  desc: null
  value: 4
test_batch_size:
  desc: null
  value: 10
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.1
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 42
log_interval:
  desc: null
  value: 10
